name: bridge_example
description: An example of how the bridge arch works

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bridgestate:
    git:
        url: https://github.com/onuohasilver/bridges.git
        ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

